# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f117235f4cd739c6ee5026cd30783ddd82b1dc80e4266de1af62a20ce5499835f6f37764bcf6f996bcaf8015ea32482aaf8deabe60e419f6f3e22264f5b10ca7

test:
  secret_key_base: 2c26cb4178be15aa92bda64eebc3cf9ae1bbfa2d5387e3b1ecb600c5f69c24e3abbd444ba64d9d0611511881867facbef5c0d63cb71c6cd74ffcd8607189f520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
